### ISSUE TITLE
iOS保存的图片背景色问题

### ISSUE THREAD

**Issue by SoalHuang** [985211yyg/ImageGallerySaver#1]
有些带透明背景的图片保存后成白色的背景。
查看代码发现是SwiftImageGallerySaverPlugin.swift的26行使用的是let newImage = image.jpegData(compressionQuality: CGFloat(quality / 100))，能否修改为pngData()，或者提供一个选项让外部选择。

**Comment by 985211yyg** [comment]
你可以拉原作者最新的库修改



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: SoalHuang ***@***.***&gt;
发送时间: 2022年3月30日 17:10
收件人: 985211yyg/ImageGallerySaver ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [985211yyg/ImageGallerySaver] iOS保存的图片背景色问题 (Issue #1)





 
有些带透明背景的图片保存后成白色的背景。
 查看代码发现是SwiftImageGallerySaverPlugin.swift的26行使用的是let newImage = image.jpegData(compressionQuality: CGFloat(quality / 100))，能否修改为pngData()，或者提供一个选项让外部选择。
